/*
 * Copyright (c) 2024, Aktiv-Soft JSC.
 * See the LICENSE file at the top-level directory of this distribution.
 * All Rights Reserved.
 */

package ru.rutoken.tech.bank

/**
 * Expires in 2045.
 */
const val BANK_CERTIFICATE_GOST = "MIIDJzCCAtKgAwIBAgIUTFWN1sTT25V/glMt7iiv0snn3V8wDAYIKoUDBwEBAwIF" +
        "ADCB6DEjMCEGA1UEAwwa0KDRg9GC0L7QutC10L0g0KLQtdGB0YIgQ0ExIzAhBgNV" +
        "BAoMGtCg0YPRgtC+0LrQtdC9INCi0LXRgdGCIENBMRcwFQYDVQQLDA7QoNGD0YLQ" +
        "vtC60LXQvTFFMEMGA1UECQw80YPQu9C40YbQsCDQqNCw0YDQuNC60L7Qv9C+0LTR" +
        "iNC40L/QvdC40LrQvtCy0YHQutCw0Y8sINC0LiA1MRUwEwYDVQQHDAzQnNC+0YHQ" +
        "utCy0LAxGDAWBgNVBAgMDzc3INCc0L7RgdC60LLQsDELMAkGA1UEBhMCUlUwHhcN" +
        "MjQwODAxMTYxMTM2WhcNNDUwMTAxMTYxMTM2WjCBxzEgMB4GA1UEAwwX0KDRg9GC" +
        "0L7QutC10L0g0JHQsNC90LoxIzAhBgNVBAoMGtCQ0J4gItCQ0LrRgtC40LIg0KHQ" +
        "vtGE0YIiMQswCQYDVQQGEwJSVTEVMBMGA1UECAwM0JzQvtGB0LrQstCwMRkwFwYD" +
        "VQQHDBDQsy4g0JzQvtGB0LrQstCwMT8wPQYDVQQJDDbQqNCw0YDQuNC60L7Qv9C+" +
        "0LTRiNC40L/QvdC40LrQvtCy0YHQutCw0Y8g0YPQuywg0LQuIDEwXjAXBggqhQMH" +
        "AQEBATALBgkqhQMHAQIBAQIDQwAEQDO0PuaaQDxYvhJyAbUlJjy7w10Rn0f3qYpp" +
        "M4LpLP77+2IlDuZSpy80OR8jAui+oZBbH4VarEVeAbx3sMHtx5ijcjBwMAwGBSqF" +
        "A2RyBAMCAQAwEwYDVR0gBAwwCjAIBgYqhQNkcQEwCwYDVR0PBAQDAgTwMB0GA1Ud" +
        "DgQWBBTbIgMZwombphKKCRVIVdXlh4L+JzAfBgNVHSMEGDAWgBTEk+PlJFCxOwKZ" +
        "5QfFtp4/9YvdcTAMBggqhQMHAQEDAgUAA0EA/KytGQd7vY8Tjj3dAZoQBmWTa36U" +
        "hDyzBcq3nubcAZHLR95PwluJVyF+ImvE+BqJp3jKX+EpSwrzCihWqu/h0Q=="

const val BANK_PRIVATE_KEY_GOST = "MEACAQAwFwYIKoUDBwEBAQEwCwYJKoUDBwECAQECBCIEILp8WYT5agaVtlBo/2CL" +
        "IJYQ20PNplP4Azl99t+tyCgi"
