/*
 * Copyright (c) 2024, Aktiv-Soft JSC.
 * See the LICENSE file at the top-level directory of this distribution.
 * All Rights Reserved.
 */

package ru.rutoken.tech.bank

/**
 * Expires in 2045.
 */
const val BANK_CERTIFICATE_GOST = "MIIDJzCCAtKgAwIBAgIUbCtwnL91xKQ/StxgzUqWk11DwuEwDAYIKoUDBwEBAwIF" +
        "ADCB6DEjMCEGA1UEAwwa0KDRg9GC0L7QutC10L0g0KLQtdGB0YIgQ0ExIzAhBgNV" +
        "BAoMGtCg0YPRgtC+0LrQtdC9INCi0LXRgdGCIENBMRcwFQYDVQQLDA7QoNGD0YLQ" +
        "vtC60LXQvTFFMEMGA1UECQw80YPQu9C40YbQsCDQqNCw0YDQuNC60L7Qv9C+0LTR" +
        "iNC40L/QvdC40LrQvtCy0YHQutCw0Y8sINC0LiA1MRUwEwYDVQQHDAzQnNC+0YHQ" +
        "utCy0LAxGDAWBgNVBAgMDzc3INCc0L7RgdC60LLQsDELMAkGA1UEBhMCUlUwHhcN" +
        "MjQwNTIyMTY0NzUxWhcNNDUwMTA5MTY0NzUxWjCBxzEgMB4GA1UEAwwX0KDRg9GC" +
        "0L7QutC10L0g0JHQsNC90LoxIzAhBgNVBAoMGtCQ0J4gItCQ0LrRgtC40LIg0KHQ" +
        "vtGE0YIiMQswCQYDVQQGEwJSVTEVMBMGA1UECAwM0JzQvtGB0LrQstCwMRkwFwYD" +
        "VQQHDBDQsy4g0JzQvtGB0LrQstCwMT8wPQYDVQQJDDbQqNCw0YDQuNC60L7Qv9C+" +
        "0LTRiNC40L/QvdC40LrQvtCy0YHQutCw0Y8g0YPQuywg0LQuIDEwXjAXBggqhQMH" +
        "AQEBATALBgkqhQMHAQIBAQIDQwAEQKUiWN82s3Z4cjGlhax7qPyGJKBjO/Ir2qcV" +
        "AiSf8eclrmSGRwyJS4ES0evD/EAdAITNsZfr238MzD+pbtnjM16jcjBwMAwGBSqF" +
        "A2RyBAMCAQAwEwYDVR0gBAwwCjAIBgYqhQNkcQEwCwYDVR0PBAQDAgTwMB0GA1Ud" +
        "DgQWBBReK4tzrZVLQVCQhWGCsOrdXWtufzAfBgNVHSMEGDAWgBQMxonLnmDIr7Ow" +
        "y2qEA1AbaWOhDDAMBggqhQMHAQEDAgUAA0EANRopyKyFyApCXPmn1oF0Np679PGF" +
        "O4gZjF3Vgy5HebUqAGNaD9aqogGJxvYdwzjxCH62GO5mGyjW2/3g/NkCQQ=="

const val BANK_PRIVATE_KEY_GOST = "MEACAQAwFwYIKoUDBwEBAQEwCwYJKoUDBwECAQECBCIEICoHpshpBACCNPNrhZeh" +
        "pPt/5OLxdXCAwM+OpiyG5tLw"
