package ru.rutoken.tech.utils

/**
 * Expires in 2045.
 */
const val BANK_CERTIFICATE_GOST = "MIIBEjCBwKADAgECAgEBMAoGCCqFAwcBAQMCMA8xDTALBgNVBAMMBFRFU1QwHhcNMTgwNjA2MTAyNzA4Wh" +
        "cNNDUxMDIyMTAyNzA4WjAPMQ0wCwYDVQQDDARURVNUMGgwIQYIKoUDBwEBAQEwFQYJKoUDBwECAQECBggqhQMHAQECAgNDAARA9JxhRZPB5e" +
        "TCHirU/iJc+k6ap8PfUXiwqOmDLzYIct77Q0NXqWBHRdn/rtr8GY89bnoJc4zwaDbuSwfkGmKbXjAKBggqhQMHAQEDAgNBAHjQxA8FN3Q9B0" +
        "K/waQr4QKSboYOj1dr5RaVDyXs99l223icKwh+EQ4zq61iiX1J1ekbDygDrK9n6NXiZBylVEg="

const val BANK_PRIVATE_KEY_GOST = "MEoCAQAwIQYIKoUDBwEBAQEwFQYJKoUDBwECAQECBggqhQMHAQECAgQiBCDsFPZlHkN0G8OOtKeyUODbIo" +
        "6qZ9j1uw2Jv/ni++vm6w=="
